include $(CLEAR_VARS)
md5.o: libs/md5.h
	$(CC) $(CFLAGS) -o libs/md5.o -c libs/md5.c

crc32.o: libs/crc32.h
	$(CC) $(CFLAGS) -o libs/crc32.o -c libs/crc32.c

allocator.o: libs/allocator.h
	$(CC) $(CFLAGS) -o libs/allocator.o -c libs/allocator.c
